name: Daily Commit Workflow

on:
  schedule:
    # Runs daily at 07:30 UTC
    - cron: "30 7 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add commit by 24f2002119@ds.study.iitm.ac.in
        run: |
          echo "Daily update on $(date)" >> daily-log.txt
          git config --local user.email "24f2002119@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add daily-log.txt
          git commit -m "Automated daily commit [skip ci]" || echo "No changes to commit"

      - name: Push changes
        run: git push
